@server = http://localhost:4005
@auth = Authorization: Basic alice:

### Main.Customers
GET {{server}}/odata/v4/main/Customers
Content-Type: application/json
{{auth}}



### Main.Customers
POST {{server}}/odata/v4/main/Customers
Content-Type: application/json
{{auth}}

{
  "name": "name-10404",
  "age": 97
}



### Main.Customers
PATCH {{server}}/odata/v4/main/Customers(6)
Content-Type: application/json
{{auth}}

{
  "name": "TESTE",
  "age": 97
}


### Main.Customers
DELETE {{server}}/odata/v4/main/Customers(6)
Content-Type: application/json
{{auth}}
